package challengeme.backend.controller;

import challengeme.backend.dto.request.create.UserCreateRequest;
import challengeme.backend.mapper.UserMapper;
import challengeme.backend.model.User;
import challengeme.backend.repository.UserRepository;
import challengeme.backend.security.JwtUtils;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * Controller responsible for handling authentication requests.
 * Provides endpoints for user login, registration (signup), and session validation.
 * Uses JWT (JSON Web Tokens) for stateless authentication.
 */
@CrossOrigin(origins = "*", maxAge = 3600)
@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
public class AuthController {

    private final AuthenticationManager authenticationManager;
    private final UserRepository userRepository;
    private final PasswordEncoder encoder;
    private final JwtUtils jwtUtils;
    private final UserMapper userMapper;

    /**
     * Authenticates a user based on credentials and generates a JWT token.
     * Supports both email and username as identifiers.
     * * @param loginRequest a map containing "emailOrUsername" (or "username") and "password".
     * @return a ResponseEntity containing the JWT token and the authenticated user's data.
     */
    @PostMapping("/login")
    public ResponseEntity<?> authenticateUser(@RequestBody Map<String, String> loginRequest) {
        String identifier = loginRequest.get("emailOrUsername");
        if (identifier == null) identifier = loginRequest.get("username");
        String password = loginRequest.get("password");

        // Authenticate the user through Spring Security's AuthenticationManager
        Authentication authentication = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(identifier, password));

        // Set the authentication in the security context
        SecurityContextHolder.getContext().setAuthentication(authentication);

        // Generate the JWT string
        String jwt = jwtUtils.generateJwtToken(authentication);

        UserDetails userDetails = (UserDetails) authentication.getPrincipal();
        User user = userRepository.findByUsername(userDetails.getUsername())
                .orElseThrow(() -> new RuntimeException("Error: User not found post-auth."));

        Map<String, Object> response = new HashMap<>();
        response.put("token", jwt);
        response.put("user", userMapper.toDTO(user));
        return ResponseEntity.ok(response);
    }

    /**
     * Registers a new user in the system.
     * Validates if the username or email is already taken before persisting data.
     * * @param signUpRequest the request DTO containing user registration details.
     * @return a success message or an error map if validation fails.
     */
    @PostMapping("/signup")
    public ResponseEntity<?> registerUser(@Valid @RequestBody UserCreateRequest signUpRequest) {
        if (userRepository.existsByUsername(signUpRequest.getUsername())) {
            return ResponseEntity.badRequest().body(Map.of("error", "Username taken!"));
        }
        if (userRepository.existsByEmail(signUpRequest.getEmail())) {
            return ResponseEntity.badRequest().body(Map.of("error", "Email in use!"));
        }

        // Map request to User entity and encode password
        User user = new User();
        user.setUsername(signUpRequest.getUsername());
        user.setEmail(signUpRequest.getEmail());
        user.setPassword(encoder.encode(signUpRequest.getPassword()));
        user.setPoints(0);
        user.setRole("user");

        // Save the user (ID is auto-generated by Hibernate strategy)
        userRepository.save(user);
        return ResponseEntity.ok(Collections.singletonMap("message", "User registered successfully!"));

    }

    /**
     * Retrieves the profile of the currently authenticated user based on the security context.
     * Useful for frontend app initialization to verify if a session is still valid.
     * * @return the UserDTO of the logged-in user or 401 Unauthorized if no valid session exists.
     */
    @GetMapping("/me")
    public ResponseEntity<?> getCurrentUser() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated() || authentication.getPrincipal().equals("anonymousUser")) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }
        User user = userRepository.findByUsername(authentication.getName())
                .orElseThrow(() -> new RuntimeException("Error: User not found."));
        return ResponseEntity.ok(userMapper.toDTO(user));
    }
}